apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: backend
  name: {{ .Release.Name }}-deploy
  namespace: "{{ .Values.backend.namespace }}"
spec:
  replicas: "{{ .Values.backend.replicaset }}"
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - env:
            - name: COLOR
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: COLOR
          image: oziomauzoma/backend:v1
          imagePullPolicy: Always
          name: sample-backend
          ports:
            - containerPort: "{{ .Values.backend.port }}"
              protocol: TCP