apiVersion: v1
kind: Service
metadata:
  labels:
    type: backend
  name: {{ .Release.Name }}-service
  namespace: "{{ .Values.backend.namespace }}"
spec:
  ports:
    - name: "80" 
      port: "{{ .Values.backend.port }}"
      targetPort: "{{ .Values.backend.targetport}}"
  selector:
    type: backend